apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "record-agent.fullname" . }}
rules:
  # TODO: add rules required by the agent (e.g. node/pod read access).
  []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "record-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "record-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
